wandb_version: 1

env_name:
  desc: null
  value: coin3
note:
  desc: null
  value: null
num_agents:
  desc: null
  value: 3
rollout_len:
  desc: null
  value: 1000
total_timesteps:
  desc: null
  value: 300000000.0
use_collective_reward:
  desc: null
  value: false
inequity_averse_reward:
  desc: null
  value: false
alpha:
  desc: null
  value: 5
beta:
  desc: null
  value: 0.05
l:
  desc: null
  value: 1
gpu:
  desc: null
  value: 0
num_cpus:
  desc: null
  value: 4
num_envs:
  desc: null
  value: 12
seed:
  desc: null
  value: 1
eval_interval:
  desc: null
  value: 4000
eval_episodes:
  desc: null
  value: 1
user_name:
  desc: null
  value: '1160677229'
aga:
  desc: null
  value: false
selfish_level:
  desc: null
  value: 1.0
play_altruistic_game:
  desc: null
  value: false
altruistic_model:
  desc: null
  value: A
alt_alpha:
  desc: null
  value: 0.0
num_frames:
  desc: null
  value: 6
features_dim:
  desc: null
  value: 128
fcnet_hiddens:
  desc: null
  value:
  - 1024
  - 128
ent_coef:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 500
n_epochs:
  desc: null
  value: 30
gae_lambda:
  desc: null
  value: 1.0
gamma:
  desc: null
  value: 0.99
target_kl:
  desc: null
  value: 0.05
grad_clip:
  desc: null
  value: 40
verbose:
  desc: null
  value: 0
view_len:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.001
lr_schedule_args:
  desc: null
  value:
    lr: 0.001
    steps: 50000000
    weight: 0.1
l_schedule_args:
  desc: null
  value:
    l: 1
    steps: 50000000
    weight: 1
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706005909.320546
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
