wandb_version: 1

env_name:
  desc: null
  value: coin3
num_agents:
  desc: null
  value: 3
num_cpus:
  desc: null
  value: 1
num_envs:
  desc: null
  value: 2
kl_threshold:
  desc: null
  value: 0.01
rollout_len:
  desc: null
  value: 1000
total_timesteps:
  desc: null
  value: 500000000.0
use_collective_reward:
  desc: null
  value: true
inequity_averse_reward:
  desc: null
  value: false
alpha:
  desc: null
  value: 0.55
beta:
  desc: null
  value: 0.05
seed:
  desc: null
  value: 42
user_name:
  desc: null
  value: '1160677229'
model:
  desc: null
  value: causal
using_reward_timestep:
  desc: null
  value: 2000000
extractor:
  desc: null
  value: cnn
enable_trajs_learning:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    code_path: code/run_scripts/sb3_independent.py
    python_version: 3.8.10
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709116111.555314
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 30
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
